print ("What do you call a strawberry to a scientist?")
print ("A Fragaria × ananassa!")
print ("Wait no that's not a joke...")
print ("What do you get when a- wait no I can't remember The Joker reference.")
print ("Ah, here's one! What do you get when... you cross the chicken with the road?")
print ("...Roadkill? Something otherside?")
print ("Eh, I wish I could come up with a corny joke but I'm just not corn!")
print ("...Wait... that wasn't a joke.")
print ("Umm... print (funny joke)")
print ("Wait no it was never meant to be funny, it was meant to be corny! Right?")
print ("Ah, no! I've got it now!")
print ("This is the story about a man named Stanley")
print ("Stanley worked in a big office building where he was employee 427.")
print ("Employee 427's job was simple: He sat at his desk in room 427 and pressed buttons-")
print ("Wait, no! That's the script for The Stanley Parable! Let's just start over.")
print ("Umm..............................................................turtles :D")
print ("NO WAIT! TURTLES AREN'T A CORNY JOKE! AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-ooh!")
print ("What did the cat say to the hotdog when the hotdog asked what his favorite subject was?")
print ("Lunch.")
print ("^  ^")
print ("⊥ ⊥")
print (" ¿ ")
print ("___")
print ("\_/")
print ("Wait, that joke doesn't make any sense.")
print ("Umm... Alright just pretend I somehow coded a corny joke here, along with the entirety of minecraft somehow just with the next single line of code")
print (9+10)