import os
import time
os.system('color 55')
end = input("press any key to change colors")
os.system('color f2')
end = input("press any key to change")
os.system('color a4')
end = input("press any key to")
os.system('color 69')
end = input("press any key")
os.system('color 10')
end = input("press any")
os.system('color 23')
end = input("press")
os.system('color 0f')
end = input("")
os.system('color a5')
end = input("please")
os.system('color a4')
end = input("please can")
os.system('color 46')
end = input("please can you")
os.system('color 42')
end = input("please can you help")
os.system('color 9f')
end = input("please can you help the")
os.system('color f0')
end = input("please can you help the os?")
os.system('color ac')
print("...")
for i in range(10,100):
    thelist = ['color ', str(i)]
    time.sleep(1)
    os.system(''.join(thelist))
    print("colors...")